//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcorp.Timesheet.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeableHoursBalance
    {
        public System.Guid Id { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public System.DateTime RunOn { get; set; }
        public decimal BillableHours { get; set; }
        public bool IsCurrentMonth { get; set; }
    }
}
