//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcorp.Timesheet.DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TimeSheetsDataContext : DbContext
    {
        public TimeSheetsDataContext()
            : base("name=TimeSheetsDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChargeableHoursBalance> ChargeableHoursBalances { get; set; }
    
        public virtual ObjectResult<MonthlyProgress_ChargeableHours_Result> MonthlyProgress_ChargeableHours(string employeeId)
        {
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonthlyProgress_ChargeableHours_Result>("MonthlyProgress_ChargeableHours", employeeIdParameter);
        }
    
        public virtual ObjectResult<EmployeeAllocatedProjects_Result> EmployeeAllocatedProjects(string employeeId)
        {
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeAllocatedProjects_Result>("EmployeeAllocatedProjects", employeeIdParameter);
        }
    }
}
