//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcorp.Timesheets
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTime
    {
        public System.Guid EmployeeTimeID { get; set; }
        public System.DateTime CapturedDate { get; set; }
        public int ChargableTime { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectOwner { get; set; }
        public string Client { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public int TotalBillableHours { get; set; }
        public string Comments { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
